export const api = {
  AUTH: {
    AGENCY_LOGIN: "/auth/agency/login",
    ADMIN_LOGIN: "/auth/admin/login",
    CANDIDATE_LOGIN: "/auth/candidate/login",
    STAFF_LOGIN: "/auth/staff/login",
    REGISTER: "/auth/signup",
    VERIFY_REGISTER: "/auth/verify-signup",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    RESENT_OTP_VERIFICATION: "/auth/resend-verification",
    RESET_PASSWORD: "/auth/reset-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    CHANGE_PASSWORD: "/auth/change-password",
    REFRESH_TOKEN: "/auth/refresh-token",
  },
  ADMIN: {
    GET_AGENCY: "/admin/agency/profiles",
    GET_AGENCY_PROFILE_DETAILS: "/admin/agency/profiles/{userId}",
    PROCESS_AGENCY_PROFILE: "/admin/agency/profiles/process",
    PROCESS_AGENCY_DOCUMENT: "/admin/agency/documents/process",
    APPROVED_COUNTRIES: "/countries/enabled",
    ALL_COUNTRIES: "/countries/search",
    TOGGLE_COUNTRY: "/countries/{id}/toggle",
    DASHBOARD: "/admin/dashboard",
    JOBS: {
      CREATE: "/admin/jobs",
      GET_JOB: "/admin/jobs",
      GET_JOB_BY_ID: "/admin/jobs/{id}",
      ASSIGN: "/admin/jobs/assign",
    },
    APPLICATIONS: {
      GET: "/admin/applications",
      GET_BY_ID: "/admin/applications/{id}",
      UPDATE_STATUS: "/admin/applications/{id}/status",
      PROCESS_AGENCY_DOCUMENT: "/admin/agency/documents/process",
      SELF_APPLICATIONS: "/admin/self-applications",
      UPDATE_SELF_APPLICATION: "/admin/self-applications/{applicationId}/status",
      GET_SELF_APPLICATION_BY_ID: "/admin/self-applications/{applicationId}",
      PROCESS_SELF_DOCUMENT: "/admin/self-applications/documents/process",
    },
    INTERVIEWS: {
      GET: "/admin/interviews",
      GET_BY_ID: "/admin/interviews/{interviewId}",
      GET_BY_APPLICATION_ID: "/admin/interviews/application/{jobApplicationId}",
      CREATE_OR_UPDATE: "/admin/interviews",
      SET_RESULT: "/admin/interviews/{interviewId}/result",
      UPDATE_STATUS: "/admin/interviews/{interviewId}/status",
      CANCEL: "/admin/interviews/{interviewId}/cancel",
      DELETE: "/admin/interviews/{interviewId}",
      SHORTLISTED: "/admin/shortlisted",
      SHORTLISTED_BY_ID: "/admin/shortlisted/{applicationId}",
    },
    ANNOUNCEMENTS: {
      CREATE: "/admin/announcements",
      GET_ALL: "/admin/announcements",
      GET_BY_ID: "/admin/announcements/{id}",
      UPDATE: "/admin/announcements/{id}",
      DELETE: "/admin/announcements/{id}",
      PIN: "/admin/announcements/{id}/pin",
    }
  },
  AGENCY: {
    DASHBOARD: "/agency/dashboard",
    GET_PROFILE: "/agency/profile",
    UPDATE_PROFILE: "/agency/profile",
    APPROVED_PROFILE: "/agency/profile/complete",
    CREATE_PROFILE: "/agency/profile",
    UPLOAD_DOCUMENT: "/agency/documents/upload",
    CANDIDATES: {
      GET: "/agency/candidates",
      POST: "/agency/candidates",
      GET_BY_ID: "/agency/candidates/{id}",
      UPLOAD_DOCUMENT: "/agency/candidates/{candidateId}/documents/upload",
    },
    JOBS: {
      APPLY: "/agency/applications",
      GET_JOBS: "/agency/jobs/assigned",
      GET_APPLICATIONS: "/agency/applications",
      GET_APPLICATION_BY_ID: "/agency/applications/{id}",
      WITHDRAW: "/agency/applications/{id}/withdraw",
    },
    INTERVIEWS: {
      GET: "/agency/interviews",
      GET_BY_ID: "/agency/interviews/{interviewId}",
    },
    ANNOUNCEMENTS: {
      GET: "/announcements",
      GET_BY_ID: "/announcements/{id}",
      GET_LATEST: "/announcements/latest",
    },
  },
  CANDIDATE: {
    DASHBOARD: "/candidate/dashboard",
    PROFILE: "/candidate/profile",
    CREATE_PROFILE: "/candidate/profile",
    UPLOAD_DOCUMENT: "/candidate/documents/upload",
    JOBS: "/public/jobs",
    APPLY_JOB: "/candidate/jobs/{jobDemandId}/apply",
    APPLICATIONS: {
      GET: "/candidate/applications",
      POST: "/candidate/applications",
      GET_BY_ID: "/candidate/applications/{applicationId}",
      WITHDRAW: "/candidate/applications/{applicationId}/withdraw",
    },
    INTERVIEWS: {
      GET: "/candidate/interviews",
      GET_BY_ID: "/candidate/interviews/{interviewId}",
    },
    ANNOUNCEMENTS: {
      GET: "/announcements",
      GET_BY_ID: "/announcements/{id}",
      GET_LATEST: "/announcements/latest",
    },
  },
};
