export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/register",
  VERIFY: "/register/verify",
  ADMIN_DASHBOARD: "/dashboard",
  AGENCY_DASHBOARD: "/agency/dashboard",
  AGENCY_CANDIDATES: "/agency/candidates",
  AGENCY_JOBS: "/agency/jobs",
  AGENCY_NETWORK: "/agency",
  AGENCY_APPLICATIONS: "/agency/applications",
  AGENCY_PROFILE: "/agency/profile",
  COUNTRY_MANAGEMENT: "/country-management",
  JOBS: "/job",
  APPLICATIONS: "/applications",
  CANDIDATE_DASHBOARD: "/candidate/dashboard",
  CANDIDATE_PROFILE: "/candidate/profile",
  CANDIDATE_APPLICATIONS: "/candidate/applications",
  CANDIDATE_JOBS: "/candidate/jobs",
  CANDIDATE_LOGIN: "/login/candidate",
  CANDIDATE_SIGNUP: "/register/candidate",
};
