export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/register",
  VERIFY: "/register/verify",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ADMIN_DASHBOARD: "/dashboard",
  AGENCY_DASHBOARD: "/agency/dashboard",
  AGENCY_CANDIDATES: "/agency/candidates",
  AGENCY_JOBS: "/agency/jobs",
  AGENCY_NETWORK: "/agency",
  AGENCY_APPLICATIONS: "/agency/applications",
  AGENCY_PROFILE: "/agency/profile",
  AGENCY_INTERVIEWS: "/agency/interviews",
  AGENCY_ANNOUNCEMENTS: "/agency/announcements",
  COUNTRY_MANAGEMENT: "/country-management",
  JOBS: "/job",
  INTERVIEW: "/interview",
  INTERVIEW_SCHEDULED: "/interview/scheduled",
  ADMIN_AGENCY_APPLICATIONS: "/applications/agency",
  ADMIN_SELF_APPLICATIONS: "/applications/self",
  ADMIN_ANNOUNCEMENTS: "/announcements",
  CANDIDATE_DASHBOARD: "/candidate/dashboard",
  CANDIDATE_PROFILE: "/candidate/profile",
  CANDIDATE_APPLICATIONS: "/candidate/applications",
  CANDIDATE_JOBS: "/candidate/jobs",
  CANDIDATE_INTERVIEWS: "/candidate/interviews",
  CANDIDATE_ANNOUNCEMENTS: "/candidate/announcements",
  CANDIDATE_LOGIN: "/login/candidate",
  CANDIDATE_SIGNUP: "/register/candidate",
  HOME: "/",
  PUBLIC: {
    RECRUITMENT_PROCESS: "/public/recuirement",
    SPECIALIZATION: "/public/specialization",
    ABOUT: "/public/about",
    CONTACT: "/public/contact"
  }
};
